// electron-vue/src/svelte-app/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte/internal';
  
  // State variables
  let isConnected = false;
  let clientId = null;
  let wsConnection = null;
  let namespace = 'svelte-data';
  let dataEntries = [];
  let loading = false;
  let error = null;
  
  // Form state for creating/editing data
  let editMode = false;
  let editId = null;
  let formKey = '';
  let formValue = '';
  
  // WebSocket connection
  function connectWebSocket() {
    try {
      wsConnection = window.wsAPI.connect();
      
      wsConnection.onOpen(() => {
        console.log('WebSocket connected');
        isConnected = true;
      });
      
      wsConnection.onMessage((data) => {
        console.log('WebSocket message received:', data);
        
        if (data.type === 'connection') {
          clientId = data.clientId;
          
          // Register as a Svelte renderer
          wsConnection.send({
            type: 'register',
            title: 'Svelte Data Explorer',
            type: 'svelte'
          });
        } else if (data.type === 'db-changed') {
          if (data.namespace === namespace) {
            loadData();
          }
        }
      });
      
      wsConnection.onClose(() => {
        console.log('WebSocket disconnected');
        isConnected = false;
        clientId = null;
        
        // Try to reconnect after a delay
        setTimeout(() => {
          connectWebSocket();
        }, 3000);
      });
      
      wsConnection.onError((err) => {
        console.error('WebSocket error:', err);
        isConnected = false;
        error = 'Connection error';
      });
    } catch (err) {
      console.error('Failed to connect to WebSocket server:', err);
      isConnected = false;
      error = 'Connection failed';
    }
  }
  
  // Load data from the database
  async function loadData() {
    loading = true;
    error = null;
    
    try {
      const result = await window.electronAPI.dbGetAll(namespace);
      
      if (result.success) {
        // Convert object to array of entries for easier rendering in Svelte
        dataEntries = Object.entries(result.values || {}).map(([key, value]) => ({
          key,
          value,
          type: typeof value,
          displayValue: formatValue(value)
        }));
      } else {
        console.error('Failed to load data:', result.error);
        error = result.error;
        dataEntries = [];
      }
    } catch (err) {
      console.error('Error loading data:', err);
      error = err.message;
      dataEntries = [];
    } finally {
      loading = false;
    }
  }
  
  // Format value for display
  function formatValue(value) {
    if (typeof value === 'object') {
      return JSON.stringify(value, null, 2);
    }
    return String(value);
  }
  
  // Parse form value based on content
  function parseValue(input) {
    try {
      if (input.trim().startsWith('{') || input.trim().startsWith('[')) {
        return JSON.parse(input);
      } else if (input === 'true' || input === 'false') {
        return input === 'true';
      } else if (!isNaN(Number(input))) {
        return Number(input);
      }
    } catch (err) {
      console.warn('Could not parse value as JSON, using as string');
    }
    return input;
  }
  
  // Save data to database
  async function saveData() {
    if (!formKey) return;
    
    try {
      const parsedValue = parseValue(formValue);
      
      const result = await window.electronAPI.dbSet(
        namespace,
        formKey,
        parsedValue
      );
      
      if (result.success) {
        // Reset form
        formKey = '';
        formValue = '';
        editMode = false;
        editId = null;
        
        // Reload data
        await loadData();
      } else {
        console.error('Failed to save data:', result.error);
        error = result.error;
      }
    } catch (err) {
      console.error('Error saving data:', err);
      error = err.message;
    }
  }
  
  // Delete data from database
  async function deleteData(key) {
    try {
      const result = await window.electronAPI.dbDelete(namespace, key);
      
      if (result.success) {
        // Reload data
        await loadData();
      } else {
        console.error('Failed to delete data:', result.error);
        error = result.error;
      }
    } catch (err) {
      console.error('Error deleting data:', err);
      error = err.message;
    }
  }
  
  // Edit existing data
  function editData(entry) {
    editMode = true;
    editId = entry.key;
    formKey = entry.key;
    formValue = entry.displayValue;
  }
  
  // Reset form
  function resetForm() {
    editMode = false;
    editId = null;
    formKey = '';
    formValue = '';
    error = null;
  }
  
  // Initialize on component mount
  onMount(() => {
    connectWebSocket();
    loadData();
    
    // Set up listener for database changes
    const unsubscribe = window.electronAPI.onDbChanged((data) => {
      if (data.namespace === namespace) {
        loadData();
      }
    });
    
    return () => {
      unsubscribe();
    };
  });
  
  // Clean up on component destroy
  onDestroy(() => {
    if (wsConnection) {
      wsConnection.close();
    }
  });
</script>

<main class="svelte-app">
  <header>
    <h1>Svelte Data Explorer</h1>
    <div class="connection-status" class:connected={isConnected}>
      {isConnected ? 'Connected' : 'Disconnected'}
    </div>
  </header>
  
  <div class="content">
    <section class="data-section">
      <div class="section-header">
        <h2>Data Explorer</h2>
        <div class="namespace-control">
          <input 
            type="text" 
            bind:value={namespace} 
            placeholder="Namespace"
          />
          <button on:click={loadData} class="btn primary">Load</button>
        </div>
      </div>
      
      {#if error}
        <div class="error-message">
          <p>{error}</p>
          <button on:click={() => error = null} class="btn small">Dismiss</button>
        </div>
      {/if}
      
      {#if loading}
        <div class="loading">Loading data...</div>
      {:else if dataEntries.length === 0}
        <div class="empty-state">
          <p>No data found in namespace "{namespace}"</p>
        </div>
      {:else}
        <div class="data-list">
          {#each dataEntries as entry (entry.key)}
            <div class="data-card">
              <div class="data-header">
                <h3>{entry.key}</h3>
                <div class="data-type">{entry.type}</div>
              </div>
              <div class="data-content">
                <pre>{entry.displayValue}</pre>
              </div>
              <div class="data-actions">
                <button on:click={() => editData(entry)} class="btn small secondary">Edit</button>
                <button on:click={() => deleteData(entry.key)} class="btn small danger">Delete</button>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </section>
    
    <section class="form-section">
      <h2>{editMode ? 'Edit Data' : 'Create New Data'}</h2>
      
      <div class="form">
        <div class="form-group">
          <label for="key">Key</label>
          <input 
            id="key" 
            type="text" 
            bind:value={formKey} 
            disabled={editMode}
            placeholder="Enter key"
          />
        </div>
        
        <div class="form-group">
          <label for="value">Value</label>
          <textarea 
            id="value" 
            bind:value={formValue} 
            placeholder="Enter value (string, number, or JSON)"
            rows="6"
          ></textarea>
        </div>
        
        <div class="form-actions">
          <button 
            on:click={saveData} 
            class="btn primary" 
            disabled={!formKey || !formValue}
          >
            {editMode ? 'Update' : 'Save'}
          </button>
          
          <button on:click={resetForm} class="btn secondary">
            {editMode ? 'Cancel' : 'Clear'}
          </button>
        </div>
      </div>
    </section>
  </div>
  
  <footer>
    <div class="client-info">
      <div>Client ID: {clientId || 'Not connected'}</div>
      <div>Renderer Type: Svelte</div>
    </div>
  </footer>
</main>

<style>
  /* Styles will be in the separate CSS file */
</style>

// electron-vue/src/vue-app/App.vue
<template>
  <div class="vue-app">
    <header>
      <h1>Vue Renderer</h1>
      <div class="connection-status" :class="{ connected: isConnected }">
        {{ isConnected ? 'Connected' : 'Disconnected' }}
      </div>
    </header>

    <main>
      <section class="data-section">
        <h2>Shared Data Viewer</h2>
        
        <div class="namespace-controls">
          <input 
            v-model="namespace" 
            placeholder="Enter namespace"
            @keyup.enter="loadData"
          />
          <button @click="loadData" class="btn primary">Load Data</button>
        </div>

        <div v-if="!namespace" class="empty-state">
          Enter a namespace to load data
        </div>
        
        <div v-else-if="loading" class="loading">
          Loading data...
        </div>
        
        <div v-else-if="Object.keys(data).length === 0" class="empty-state">
          No data found in namespace "{{ namespace }}"
        </div>
        
        <div v-else class="data-container">
          <div 
            v-for="(value, key) in data" 
            :key="key"
            class="data-item"
          >
            <div class="data-key">{{ key }}</div>
            <div class="data-value">
              <pre>{{ formatValue(value) }}</pre>
            </div>
          </div>
        </div>
      </section>

      <section class="editor-section">
        <h2>Data Editor</h2>
        
        <div class="editor-form">
          <div class="form-group">
            <label for="dataKey">Key</label>
            <input 
              id="dataKey"
              v-model="newKey" 
              placeholder="Enter key"
            />
          </div>
          
          <div class="form-group">
            <label for="dataValue">Value</label>
            <textarea 
              id="dataValue"
              v-model="newValue" 
              placeholder="Enter value (string, number, or JSON)"
              rows="5"
            ></textarea>
          </div>
          
          <div class="form-actions">
            <button 
              @click="saveData" 
              class="btn primary"
              :disabled="!canSave"
            >
              Save Data
            </button>
            <button 
              @click="clearForm" 
              class="btn secondary"
            >
              Clear
            </button>
          </div>
        </div>
      </section>
    </main>

    <footer>
      <div class="client-info">
        <div>Client ID: {{ clientId || 'Not connected' }}</div>
        <div>Renderer Type: Vue</div>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'VueApp',
  data() {
    return {
      isConnected: false,
      clientId: null,
      wsConnection: null,
      namespace: '',
      data: {},
      loading: false,
      newKey: '',
      newValue: '',
      editingKey: null
    };
  },
  computed: {
    canSave() {
      return this.namespace && this.newKey && this.newValue;
    }
  },
  mounted() {
    this.connectWebSocket();
    
    // Listen for database changes
    window.electronAPI.onDbChanged((data) => {
      if (data.namespace === this.namespace) {
        this.loadData();
      }
    });
  },
  beforeUnmount() {
    if (this.wsConnection) {
      this.wsConnection.close();
    }
  },
  methods: {
    connectWebSocket() {
      try {
        this.wsConnection = window.wsAPI.connect();
        
        this.wsConnection.onOpen(() => {
          console.log('WebSocket connected');
          this.isConnected = true;
        });
        
        this.wsConnection.onMessage((data) => {
          console.log('WebSocket message received:', data);
          
          if (data.type === 'connection') {
            this.clientId = data.clientId;
            
            // Register as a Vue renderer
            this.wsConnection.send({
              type: 'register',
              title: 'Vue Data Viewer',
              type: 'vue'
            });
          } else if (data.type === 'db-changed') {
            if (data.namespace === this.namespace) {
              this.loadData();
            }
          }
        });
        
        this.wsConnection.onClose(() => {
          console.log('WebSocket disconnected');
          this.isConnected = false;
          this.clientId = null;
          
          // Try to reconnect after a delay
          setTimeout(() => {
            this.connectWebSocket();
          }, 3000);
        });
        
        this.wsConnection.onError((error) => {
          console.error('WebSocket error:', error);
          this.isConnected = false;
        });
      } catch (error) {
        console.error('Failed to connect to WebSocket server:', error);
        this.isConnected = false;
      }
    },
    
    async loadData() {
      if (!this.namespace) return;
      
      this.loading = true;
      
      try {
        const result = await window.electronAPI.dbGetAll(this.namespace);
        
        if (result.success) {
          this.data = result.values || {};
        } else {
          console.error('Failed to load data:', result.error);
          this.data = {};
        }
      } catch (error) {
        console.error('Error loading data:', error);
        this.data = {};
      } finally {
        this.loading = false;
      }
    },
    
    async saveData() {
      if (!this.canSave) return;
      
      try {
        // Parse value if it looks like JSON
        let parsedValue = this.newValue;
        try {
          if (this.newValue.trim().startsWith('{') || 
              this.newValue.trim().startsWith('[')) {
            parsedValue = JSON.parse(this.newValue);
          } else if (this.newValue === 'true' || this.newValue === 'false') {
            parsedValue = this.newValue === 'true';
          } else if (!isNaN(Number(this.newValue))) {
            parsedValue = Number(this.newValue);
          }
        } catch (e) {
          // If parsing fails, use the original string value
          console.warn('Could not parse value as JSON, using as string');
        }
        
        const result = await window.electronAPI.dbSet(
          this.namespace, 
          this.newKey, 
          parsedValue
        );
        
        if (result.success) {
          // Update local data
          this.data = {
            ...this.data,
            [this.newKey]: parsedValue
          };
          
          // Clear form
          this.clearForm();
        } else {
          console.error('Failed to save data:', result.error);
          window.electronAPI.showErrorDialog('Save Error', result.error);
        }
      } catch (error) {
        console.error('Error saving data:', error);
        window.electronAPI.showErrorDialog('Save Error', error.message);
      }
    },
    
    clearForm() {
      this.newKey = '';
      this.newValue = '';
      this.editingKey = null;
    },
    
    formatValue(value) {
      if (typeof value === 'object') {
        return JSON.stringify(value, null, 2);
      }
      return String(value);
    }
  }
};
</script>

<style>
/* Component styles will be in style.css */
</style>
